spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/gdsc
    username: sa
    password: test
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update